background            #000000
foreground            #ff8800
cursor                #ff8800
selection_background  #ff8800
selection_foreground  #000000

color0                #545753
color8                #807272
color1                #cc0000
color9                #ef2828
color2                #4e9a05
color10               #8ae234
color3                #c4a000
color11               #fce94e
color4                #5588dd
color12               #88ccff
color5                #fd3db5
color13               #ff3dff
color6                #34989a
color14               #68e2e2
color7                #efc7c7
color15               #ffdddd
