
wintypes:
{
    normal = { };
    dialog = { };
    utility = { };
    tooltip = { };
    dock = { };
    dropdown_menu = { };
    popup_menu = { };
    splash = { };
    notification = { };
    combo = { };
    dnd = { };
    menu = { };
    # For Visual Paradigm
    unknown = { blur-background = false; shadow = false; opacity = 1.0; };
};
