#! /bin/sh

# bspc config

#bspc monitor -d 1 2 3 4 5 6 7 8 9 10
bspc monitor -d 一 二 三 四 五 六 七 八 九 十

#bspc config active_border_color 	"#AA0000"
bspc config focused_border_color 	"#660000"
bspc config normal_border_color 	"#230000"
#bspc config presel_feedback_color 	"#AA000"

bspc config border_width	4
bspc config window_gap      8

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

# rules for apps 

bspc rule -a install4j-RV state=floating
bspc rule -a "linoffice" state=floating
bspc rule -a steam_app_2666510 state=pseudo_tiled split_dir=south split_ratio 340 locked private layer=above rectangle=1920x340+0+740

# utils

~/.config/bspwm/autostart &
